<?php

namespace Container0M0gQq4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaison2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fwmCM8N.App\Entity\Maison' shared service.
     *
     * @return \App\Entity\Maison
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fwmCM8N": it references class "App\\Entity\\Maison" but no such service exists.');
    }
}
