<?php

namespace Container0M0gQq4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZaQ6efZ.App\Entity\Personne' shared service.
     *
     * @return \App\Entity\Personne
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZaQ6efZ": it references class "App\\Entity\\Personne" but no such service exists.');
    }
}
