<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TLoA_HnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TLoA.Hn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TLoA.Hn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'maladie' => ['privates', '.errored..service_locator.TLoA.Hn.App\\Entity\\Maladie', NULL, 'Cannot autowire service ".service_locator.TLoA.Hn": it references class "App\\Entity\\Maladie" but no such service exists.'],
            'maladieRepository' => ['privates', 'App\\Repository\\MaladieRepository', 'getMaladieRepositoryService', true],
        ], [
            'maladie' => 'App\\Entity\\Maladie',
            'maladieRepository' => 'App\\Repository\\MaladieRepository',
        ]);
    }
}
