<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NhBUwOvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nhBUwOv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nhBUwOv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeArbreRepository' => ['privates', 'App\\Repository\\TypeArbreRepository', 'getTypeArbreRepositoryService', true],
        ], [
            'typeArbreRepository' => 'App\\Repository\\TypeArbreRepository',
        ]);
    }
}
