<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LpkDEVXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lpkDEVX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lpkDEVX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'type_maladie' => ['privates', '.errored..service_locator.lpkDEVX.App\\Entity\\TypeMaladie', NULL, 'Cannot autowire service ".service_locator.lpkDEVX": it references class "App\\Entity\\TypeMaladie" but no such service exists.'],
        ], [
            'type_maladie' => 'App\\Entity\\TypeMaladie',
        ]);
    }
}
