<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SxKO9t9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sxKO9t9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sxKO9t9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeArbre' => ['privates', '.errored..service_locator.sxKO9t9.App\\Entity\\TypeArbre', NULL, 'Cannot autowire service ".service_locator.sxKO9t9": it references class "App\\Entity\\TypeArbre" but no such service exists.'],
        ], [
            'typeArbre' => 'App\\Entity\\TypeArbre',
        ]);
    }
}
