<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P8TLCsWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P8TLCsW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P8TLCsW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'celluleRepository' => ['privates', 'App\\Repository\\CelluleRepository', 'getCelluleRepositoryService', true],
            'maisonRepository' => ['privates', 'App\\Repository\\MaisonRepository', 'getMaisonRepositoryService', true],
            'personneRepository' => ['privates', 'App\\Repository\\PersonneRepository', 'getPersonneRepositoryService', true],
            'secteurRepository' => ['privates', 'App\\Repository\\SecteurRepository', 'getSecteurRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.P8TLCsW.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.P8TLCsW": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'celluleRepository' => 'App\\Repository\\CelluleRepository',
            'maisonRepository' => 'App\\Repository\\MaisonRepository',
            'personneRepository' => 'App\\Repository\\PersonneRepository',
            'secteurRepository' => 'App\\Repository\\SecteurRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
