<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArbreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IidV.4G.App\Entity\Arbre' shared service.
     *
     * @return \App\Entity\Arbre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IidV.4G": it references class "App\\Entity\\Arbre" but no such service exists.');
    }
}
