<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClasse2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.581Eb2P.App\Entity\Classe' shared service.
     *
     * @return \App\Entity\Classe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.581Eb2P": it references class "App\\Entity\\Classe" but no such service exists.');
    }
}
