<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaladie2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.egvK0ev.App\Entity\Maladie' shared service.
     *
     * @return \App\Entity\Maladie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.egvK0ev": it references class "App\\Entity\\Maladie" but no such service exists.');
    }
}
