<?php

namespace ContainerGWbxOD6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeMaladie2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lLcUlUB.App\Entity\TypeMaladie' shared service.
     *
     * @return \App\Entity\TypeMaladie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lLcUlUB": it references class "App\\Entity\\TypeMaladie" but no such service exists.');
    }
}
