<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Secteur extends \App\Entity\Secteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'nom_secteur', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'cellule', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'maisons'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'nom_secteur', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'cellule', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Secteur' . "\0" . 'maisons'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Secteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSecteur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSecteur', []);

        return parent::getNomSecteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSecteur(string $nom_secteur): \App\Entity\Secteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSecteur', [$nom_secteur]);

        return parent::setNomSecteur($nom_secteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCellule(): ?\App\Entity\Cellule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCellule', []);

        return parent::getCellule();
    }

    /**
     * {@inheritDoc}
     */
    public function setCellule(?\App\Entity\Cellule $cellule): \App\Entity\Secteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCellule', [$cellule]);

        return parent::setCellule($cellule);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeImmutable $updatedAt): \App\Entity\Secteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): \App\Entity\Secteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaisons(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaisons', []);

        return parent::getMaisons();
    }

    /**
     * {@inheritDoc}
     */
    public function addMaison(\App\Entity\Maison $maison): \App\Entity\Secteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMaison', [$maison]);

        return parent::addMaison($maison);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMaison(\App\Entity\Maison $maison): \App\Entity\Secteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMaison', [$maison]);

        return parent::removeMaison($maison);
    }

}
