<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \App\Entity\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'lieu_naissance', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'situation_matrimoniale', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'maison', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'eleves'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'lieu_naissance', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'situation_matrimoniale', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'maison', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'eleves'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(\DateTimeInterface $date_naissance): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$date_naissance]);

        return parent::setDateNaissance($date_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuNaissance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuNaissance', []);

        return parent::getLieuNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuNaissance(string $lieu_naissance): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuNaissance', [$lieu_naissance]);

        return parent::setLieuNaissance($lieu_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(string $sexe): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationMatrimoniale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationMatrimoniale', []);

        return parent::getSituationMatrimoniale();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituationMatrimoniale(string $situation_matrimoniale): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituationMatrimoniale', [$situation_matrimoniale]);

        return parent::setSituationMatrimoniale($situation_matrimoniale);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaison(): ?\App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaison', []);

        return parent::getMaison();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaison(?\App\Entity\Maison $maison): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaison', [$maison]);

        return parent::setMaison($maison);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeImmutable $updatedAt): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\User $user): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\User $user): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getEleves(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEleves', []);

        return parent::getEleves();
    }

    /**
     * {@inheritDoc}
     */
    public function addElefe(\App\Entity\Eleve $elefe): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addElefe', [$elefe]);

        return parent::addElefe($elefe);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElefe(\App\Entity\Eleve $elefe): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElefe', [$elefe]);

        return parent::removeElefe($elefe);
    }

}
