<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Maison extends \App\Entity\Maison implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'nom_maison', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'code_maison', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'secteur', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'personnes', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'localisation', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_arbre', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'arbres', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_eau', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_electricite', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_internet', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_fosse_septique', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'qr_maison'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'nom_maison', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'code_maison', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'secteur', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'personnes', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'localisation', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_arbre', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'arbres', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_eau', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_electricite', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_internet', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'existence_fosse_septique', '' . "\0" . 'App\\Entity\\Maison' . "\0" . 'qr_maison'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Maison $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMaison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMaison', []);

        return parent::getNomMaison();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMaison(string $nom_maison): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMaison', [$nom_maison]);

        return parent::setNomMaison($nom_maison);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeMaison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeMaison', []);

        return parent::getCodeMaison();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeMaison(string $code_maison): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeMaison', [$code_maison]);

        return parent::setCodeMaison($code_maison);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecteur(): ?\App\Entity\Secteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecteur', []);

        return parent::getSecteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecteur(?\App\Entity\Secteur $secteur): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecteur', [$secteur]);

        return parent::setSecteur($secteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeImmutable $updatedAt): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonnes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonnes', []);

        return parent::getPersonnes();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersonne(\App\Entity\Personne $personne): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersonne', [$personne]);

        return parent::addPersonne($personne);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersonne(\App\Entity\Personne $personne): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersonne', [$personne]);

        return parent::removePersonne($personne);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalisation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalisation', []);

        return parent::getLocalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalisation(string $localisation): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalisation', [$localisation]);

        return parent::setLocalisation($localisation);
    }

    /**
     * {@inheritDoc}
     */
    public function isExistenceArbre(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExistenceArbre', []);

        return parent::isExistenceArbre();
    }

    /**
     * {@inheritDoc}
     */
    public function setExistenceArbre(bool $existence_arbre): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExistenceArbre', [$existence_arbre]);

        return parent::setExistenceArbre($existence_arbre);
    }

    /**
     * {@inheritDoc}
     */
    public function getArbres(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArbres', []);

        return parent::getArbres();
    }

    /**
     * {@inheritDoc}
     */
    public function addArbre(\App\Entity\Arbre $arbre): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArbre', [$arbre]);

        return parent::addArbre($arbre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArbre(\App\Entity\Arbre $arbre): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArbre', [$arbre]);

        return parent::removeArbre($arbre);
    }

    /**
     * {@inheritDoc}
     */
    public function isExistenceEau(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExistenceEau', []);

        return parent::isExistenceEau();
    }

    /**
     * {@inheritDoc}
     */
    public function setExistenceEau(bool $existence_eau): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExistenceEau', [$existence_eau]);

        return parent::setExistenceEau($existence_eau);
    }

    /**
     * {@inheritDoc}
     */
    public function isExistenceElectricite(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExistenceElectricite', []);

        return parent::isExistenceElectricite();
    }

    /**
     * {@inheritDoc}
     */
    public function setExistenceElectricite(bool $existence_electricite): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExistenceElectricite', [$existence_electricite]);

        return parent::setExistenceElectricite($existence_electricite);
    }

    /**
     * {@inheritDoc}
     */
    public function isExistenceInternet(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExistenceInternet', []);

        return parent::isExistenceInternet();
    }

    /**
     * {@inheritDoc}
     */
    public function setExistenceInternet(bool $existence_internet): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExistenceInternet', [$existence_internet]);

        return parent::setExistenceInternet($existence_internet);
    }

    /**
     * {@inheritDoc}
     */
    public function isExistenceFosseSeptique(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExistenceFosseSeptique', []);

        return parent::isExistenceFosseSeptique();
    }

    /**
     * {@inheritDoc}
     */
    public function setExistenceFosseSeptique(bool $existence_fosse_septique): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExistenceFosseSeptique', [$existence_fosse_septique]);

        return parent::setExistenceFosseSeptique($existence_fosse_septique);
    }

    /**
     * {@inheritDoc}
     */
    public function getQrMaison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQrMaison', []);

        return parent::getQrMaison();
    }

    /**
     * {@inheritDoc}
     */
    public function setQrMaison(string $qr_maison): \App\Entity\Maison
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQrMaison', [$qr_maison]);

        return parent::setQrMaison($qr_maison);
    }

}
