<?php

namespace ContainerNxt3Tag;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IidV_4GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IidV.4G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IidV.4G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'arbre' => ['privates', '.errored..service_locator.IidV.4G.App\\Entity\\Arbre', NULL, 'Cannot autowire service ".service_locator.IidV.4G": it references class "App\\Entity\\Arbre" but no such service exists.'],
        ], [
            'arbre' => 'App\\Entity\\Arbre',
        ]);
    }
}
