<?php

namespace ContainerNxt3Tag;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5ZXMtNUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5ZXMtNU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5ZXMtNU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'celluleRepository' => ['privates', 'App\\Repository\\CelluleRepository', 'getCelluleRepositoryService', true],
            'maisonRepository' => ['privates', 'App\\Repository\\MaisonRepository', 'getMaisonRepositoryService', true],
            'personneRepository' => ['privates', 'App\\Repository\\PersonneRepository', 'getPersonneRepositoryService', true],
            'quartierRepository' => ['privates', 'App\\Repository\\QuartierRepository', 'getQuartierRepositoryService', true],
            'secteurRepository' => ['privates', 'App\\Repository\\SecteurRepository', 'getSecteurRepositoryService', true],
        ], [
            'celluleRepository' => 'App\\Repository\\CelluleRepository',
            'maisonRepository' => 'App\\Repository\\MaisonRepository',
            'personneRepository' => 'App\\Repository\\PersonneRepository',
            'quartierRepository' => 'App\\Repository\\QuartierRepository',
            'secteurRepository' => 'App\\Repository\\SecteurRepository',
        ]);
    }
}
