<?php

namespace ContainerNxt3Tag;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gbw3i7OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gbw3i7O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gbw3i7O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cellule' => ['privates', '.errored..service_locator.Gbw3i7O.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.Gbw3i7O": it references class "App\\Entity\\Cellule" but no such service exists.'],
            'secteurRepository' => ['privates', 'App\\Repository\\SecteurRepository', 'getSecteurRepositoryService', true],
        ], [
            'cellule' => 'App\\Entity\\Cellule',
            'secteurRepository' => 'App\\Repository\\SecteurRepository',
        ]);
    }
}
