<?php

namespace ContainerNxt3Tag;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NPYNKrkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nPYNKrk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nPYNKrk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeMaladie' => ['privates', '.errored..service_locator.nPYNKrk.App\\Entity\\TypeMaladie', NULL, 'Cannot autowire service ".service_locator.nPYNKrk": it references class "App\\Entity\\TypeMaladie" but no such service exists.'],
            'typeMaladieRepository' => ['privates', 'App\\Repository\\TypeMaladieRepository', 'getTypeMaladieRepositoryService', true],
        ], [
            'typeMaladie' => 'App\\Entity\\TypeMaladie',
            'typeMaladieRepository' => 'App\\Repository\\TypeMaladieRepository',
        ]);
    }
}
