<?php

namespace ContainerNxt3Tag;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEleve2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S6Y87pf.App\Entity\Eleve' shared service.
     *
     * @return \App\Entity\Eleve
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.S6Y87pf": it references class "App\\Entity\\Eleve" but no such service exists.');
    }
}
