<?php

namespace ContainerNxt3Tag;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEcole2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WG1BPuz.App\Entity\Ecole' shared service.
     *
     * @return \App\Entity\Ecole
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WG1BPuz": it references class "App\\Entity\\Ecole" but no such service exists.');
    }
}
