<?php

namespace ContainerHe6Bw5K;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EsRc_JPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.esRc.jP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.esRc.jP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'celluleRepository' => ['privates', 'App\\Repository\\CelluleRepository', 'getCelluleRepositoryService', true],
            'quartier' => ['privates', '.errored..service_locator.esRc.jP.App\\Entity\\Quartier', NULL, 'Cannot autowire service ".service_locator.esRc.jP": it references class "App\\Entity\\Quartier" but no such service exists.'],
        ], [
            'celluleRepository' => 'App\\Repository\\CelluleRepository',
            'quartier' => 'App\\Entity\\Quartier',
        ]);
    }
}
