<?php

namespace ContainerHe6Bw5K;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNiveauEtude3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jMG0Y3k.App\Entity\NiveauEtude' shared service.
     *
     * @return \App\Entity\NiveauEtude
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jMG0Y3k": it references class "App\\Entity\\NiveauEtude" but no such service exists.');
    }
}
