<?php

namespace ContainerVn5Uo0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecteurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.77Arrgj.App\Entity\Secteur' shared service.
     *
     * @return \App\Entity\Secteur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.77Arrgj": it references class "App\\Entity\\Secteur" but no such service exists.');
    }
}
