<?php

namespace ContainerRw8uego;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6eHfxMrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6eHfxMr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6eHfxMr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'quartier' => ['privates', '.errored..service_locator.6eHfxMr.App\\Entity\\Quartier', NULL, 'Cannot autowire service ".service_locator.6eHfxMr": it references class "App\\Entity\\Quartier" but no such service exists.'],
        ], [
            'quartier' => 'App\\Entity\\Quartier',
        ]);
    }
}
