<?php

namespace ContainerRw8uego;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuartierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4qJg5Ix.App\Entity\Quartier' shared service.
     *
     * @return \App\Entity\Quartier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4qJg5Ix": it references class "App\\Entity\\Quartier" but no such service exists.');
    }
}
