<?php

namespace ContainerDxOmyAN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JMG0Y3kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jMG0Y3k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jMG0Y3k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'niveau_etude' => ['privates', '.errored..service_locator.jMG0Y3k.App\\Entity\\NiveauEtude', NULL, 'Cannot autowire service ".service_locator.jMG0Y3k": it references class "App\\Entity\\NiveauEtude" but no such service exists.'],
        ], [
            'niveau_etude' => 'App\\Entity\\NiveauEtude',
        ]);
    }
}
