<?php

namespace ContainerDxOmyAN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_581Eb2PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.581Eb2P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.581Eb2P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'classe' => ['privates', '.errored..service_locator.581Eb2P.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.581Eb2P": it references class "App\\Entity\\Classe" but no such service exists.'],
        ], [
            'classe' => 'App\\Entity\\Classe',
        ]);
    }
}
