<?php

namespace ContainerDxOmyAN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCellule2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MYplJyj.App\Entity\Cellule' shared service.
     *
     * @return \App\Entity\Cellule
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MYplJyj": it references class "App\\Entity\\Cellule" but no such service exists.');
    }
}
