<?php

namespace ContainerDxOmyAN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'Proxy'.\DIRECTORY_SEPARATOR.'ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Form\\CelluleSecteurType' => ['privates', 'App\\Form\\CelluleSecteurType', 'getCelluleSecteurTypeService', true],
            'App\\Form\\CelluleType' => ['privates', 'App\\Form\\CelluleType', 'getCelluleTypeService', true],
            'App\\Form\\ClasseEleveType' => ['privates', 'App\\Form\\ClasseEleveType', 'getClasseEleveTypeService', true],
            'App\\Form\\ClasseType' => ['privates', 'App\\Form\\ClasseType', 'getClasseTypeService', true],
            'App\\Form\\EcoleClasseEleveType' => ['privates', 'App\\Form\\EcoleClasseEleveType', 'getEcoleClasseEleveTypeService', true],
            'App\\Form\\EcoleClasseType' => ['privates', 'App\\Form\\EcoleClasseType', 'getEcoleClasseTypeService', true],
            'App\\Form\\EcoleType' => ['privates', 'App\\Form\\EcoleType', 'getEcoleTypeService', true],
            'App\\Form\\EleveType' => ['privates', 'App\\Form\\EleveType', 'getEleveTypeService', true],
            'App\\Form\\MaisonPersonneType' => ['privates', 'App\\Form\\MaisonPersonneType', 'getMaisonPersonneTypeService', true],
            'App\\Form\\MaisonType' => ['privates', 'App\\Form\\MaisonType', 'getMaisonTypeService', true],
            'App\\Form\\NiveauEtudeEcoleType' => ['privates', 'App\\Form\\NiveauEtudeEcoleType', 'getNiveauEtudeEcoleTypeService', true],
            'App\\Form\\NiveauEtudeType' => ['privates', 'App\\Form\\NiveauEtudeType', 'getNiveauEtudeTypeService', true],
            'App\\Form\\PersonneType' => ['privates', 'App\\Form\\PersonneType', 'getPersonneTypeService', true],
            'App\\Form\\QuartierCelluleType' => ['privates', 'App\\Form\\QuartierCelluleType', 'getQuartierCelluleTypeService', true],
            'App\\Form\\QuartierType' => ['privates', 'App\\Form\\QuartierType', 'getQuartierTypeService', true],
            'App\\Form\\SecteurMaisonType' => ['privates', 'App\\Form\\SecteurMaisonType', 'getSecteurMaisonTypeService', true],
            'App\\Form\\SecteurType' => ['privates', 'App\\Form\\SecteurType', 'getSecteurTypeService', true],
            'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService', true],
            'FM\\ElfinderBundle\\Form\\Type\\ElFinderType' => ['privates', 'fm_elfinder.form.type', 'getFmElfinder_Form_TypeService', true],
            'FOS\\CKEditorBundle\\Form\\Type\\CKEditorType' => ['privates', 'fos_ck_editor.form.type', 'getFosCkEditor_Form_TypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\CelluleSecteurType' => '?',
            'App\\Form\\CelluleType' => '?',
            'App\\Form\\ClasseEleveType' => '?',
            'App\\Form\\ClasseType' => '?',
            'App\\Form\\EcoleClasseEleveType' => '?',
            'App\\Form\\EcoleClasseType' => '?',
            'App\\Form\\EcoleType' => '?',
            'App\\Form\\EleveType' => '?',
            'App\\Form\\MaisonPersonneType' => '?',
            'App\\Form\\MaisonType' => '?',
            'App\\Form\\NiveauEtudeEcoleType' => '?',
            'App\\Form\\NiveauEtudeType' => '?',
            'App\\Form\\PersonneType' => '?',
            'App\\Form\\QuartierCelluleType' => '?',
            'App\\Form\\QuartierType' => '?',
            'App\\Form\\SecteurMaisonType' => '?',
            'App\\Form\\SecteurType' => '?',
            'App\\Form\\UserType' => '?',
            'FM\\ElfinderBundle\\Form\\Type\\ElFinderType' => '?',
            'FOS\\CKEditorBundle\\Form\\Type\\CKEditorType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
        }, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ?? ($container->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ?? ($container->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($container->privates['data_collector.form'] ?? $container->getDataCollector_FormService())));
    }
}
