<?php

namespace ContainerVfNsuii;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zw1y5sHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zw1y5sH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zw1y5sH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'maisonRepository' => ['privates', 'App\\Repository\\MaisonRepository', 'getMaisonRepositoryService', true],
            'qrcodeservice' => ['privates', 'App\\Service\\QrCodeService', 'getQrCodeServiceService', true],
            'secteur' => ['privates', '.errored..service_locator.Zw1y5sH.App\\Entity\\Secteur', NULL, 'Cannot autowire service ".service_locator.Zw1y5sH": it references class "App\\Entity\\Secteur" but no such service exists.'],
        ], [
            'maisonRepository' => 'App\\Repository\\MaisonRepository',
            'qrcodeservice' => 'App\\Service\\QrCodeService',
            'secteur' => 'App\\Entity\\Secteur',
        ]);
    }
}
