<?php

namespace ContainerVfNsuii;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0CH2vZXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0CH2vZX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0CH2vZX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'arbreRepository' => ['privates', 'App\\Repository\\ArbreRepository', 'getArbreRepositoryService', true],
            'type_arbre' => ['privates', '.errored..service_locator.0CH2vZX.App\\Entity\\TypeArbre', NULL, 'Cannot autowire service ".service_locator.0CH2vZX": it references class "App\\Entity\\TypeArbre" but no such service exists.'],
        ], [
            'arbreRepository' => 'App\\Repository\\ArbreRepository',
            'type_arbre' => 'App\\Entity\\TypeArbre',
        ]);
    }
}
