<?php

namespace ContainerVfNsuii;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EiuV8sTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EiuV8sT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EiuV8sT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'type_arbre' => ['privates', '.errored..service_locator.EiuV8sT.App\\Entity\\TypeArbre', NULL, 'Cannot autowire service ".service_locator.EiuV8sT": it references class "App\\Entity\\TypeArbre" but no such service exists.'],
        ], [
            'type_arbre' => 'App\\Entity\\TypeArbre',
        ]);
    }
}
