<?php

namespace ContainerVfNsuii;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EgvK0evService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.egvK0ev' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.egvK0ev'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'maladie' => ['privates', '.errored..service_locator.egvK0ev.App\\Entity\\Maladie', NULL, 'Cannot autowire service ".service_locator.egvK0ev": it references class "App\\Entity\\Maladie" but no such service exists.'],
        ], [
            'maladie' => 'App\\Entity\\Maladie',
        ]);
    }
}
