<?php

namespace ContainerVfNsuii;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeArbre4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sxKO9t9.App\Entity\TypeArbre' shared service.
     *
     * @return \App\Entity\TypeArbre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sxKO9t9": it references class "App\\Entity\\TypeArbre" but no such service exists.');
    }
}
