<?php

namespace ContainerLD0d9hP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2b1SjdKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2b1SjdK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2b1SjdK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eleve' => ['privates', '.errored..service_locator.2b1SjdK.App\\Entity\\Eleve', NULL, 'Cannot autowire service ".service_locator.2b1SjdK": it references class "App\\Entity\\Eleve" but no such service exists.'],
            'eleveRepository' => ['privates', 'App\\Repository\\EleveRepository', 'getEleveRepositoryService', true],
        ], [
            'eleve' => 'App\\Entity\\Eleve',
            'eleveRepository' => 'App\\Repository\\EleveRepository',
        ]);
    }
}
