<?php

namespace ContainerLD0d9hP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_77ArrgjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.77Arrgj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.77Arrgj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'maisonRepository' => ['privates', 'App\\Repository\\MaisonRepository', 'getMaisonRepositoryService', true],
            'secteur' => ['privates', '.errored..service_locator.77Arrgj.App\\Entity\\Secteur', NULL, 'Cannot autowire service ".service_locator.77Arrgj": it references class "App\\Entity\\Secteur" but no such service exists.'],
        ], [
            'maisonRepository' => 'App\\Repository\\MaisonRepository',
            'secteur' => 'App\\Entity\\Secteur',
        ]);
    }
}
