<?php

namespace ContainerLD0d9hP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCelluleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Gbw3i7O.App\Entity\Cellule' shared service.
     *
     * @return \App\Entity\Cellule
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Gbw3i7O": it references class "App\\Entity\\Cellule" but no such service exists.');
    }
}
