<?php

namespace ContainerLD0d9hP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuartier3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.esRc.jP.App\Entity\Quartier' shared service.
     *
     * @return \App\Entity\Quartier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.esRc.jP": it references class "App\\Entity\\Quartier" but no such service exists.');
    }
}
