<?php

namespace ContainerM0vNp5H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DWhTI6qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DWhTI6q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DWhTI6q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'secteurRepository' => ['privates', 'App\\Repository\\SecteurRepository', 'getSecteurRepositoryService', true],
        ], [
            'secteurRepository' => 'App\\Repository\\SecteurRepository',
        ]);
    }
}
