<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHe6Bw5K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHe6Bw5K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHe6Bw5K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHe6Bw5K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHe6Bw5K\App_KernelDevDebugContainer([
    'container.build_hash' => 'He6Bw5K',
    'container.build_id' => '0c4b77a9',
    'container.build_time' => 1653330316,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHe6Bw5K');
