<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxOmyAN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxOmyAN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDxOmyAN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDxOmyAN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDxOmyAN\App_KernelDevDebugContainer([
    'container.build_hash' => 'DxOmyAN',
    'container.build_id' => '9f95e493',
    'container.build_time' => 1652865787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxOmyAN');
